### ISSUE TITLE
为什么点一下不出内容

### ISSUE THREAD

**Issue by ic0xgkk** [hayo-studio/Alnico#18]
我测试了多次，点击卡片后，评论框多出来一个，但是文章框不展开，除非新标签打开才可以
还需要我提供什么？

**Comment by ic0xgkk** [comment]
我的博客地址
https://blog.xuegaogg.com
您去看看

**Comment by Snownee** [comment]
比较可能的原因是没更新...

**Comment by ic0xgkk** [comment]
哦好吧。。。没看到新的commit，我更新下试试
