### ISSUE TITLE
[Suggestion] Add to show the last edited time

### ISSUE THREAD

**Issue by Leiouflying** [hayo-studio/Alnico#25]
I found a very useful function on the other blog site. As we know, the Internet is developing faster than before. Lots of information are very old on the Internet. Lots of information may not work. So, I think the blog should update on time to make the information newest and make the article useful. Show the last edited time not only can tell the visitors that the article is new and it is still working but also can let the administrator arrange the article easier and better. Some times it can slove some copyright issue.

**Comment by Snownee** [comment]
8b26c4a
