### ISSUE TITLE
highlight.js connot work

### ISSUE THREAD

**Issue by Leiouflying** [hayo-studio/Alnico#27]
Lots of js cannot work on this wordpress theme. Such as _Pure Highlightjs_. I hope you can fix this problem as soon as possible.
--Update--
I am sorry, it was my wrong. The _Pure Highlightjs_ cannot work on this theme is true. But the js canbe load. I am not quite sure what's wrong on it. The _Pure Highlightjs_ can work on another theme such as _Siren_ the theme made by Louis. I cannot find the problem now. I think you can fix this problen as soon as prossibly. If you need to know more detail, I am happy to help you.

**Comment by Snownee** [comment]
能否提供此插件的链接？

**Comment by Leiouflying** [comment]
https://github.com/icodechef/Pure-Highlightjs

**Comment by Leiouflying** [comment]
I am sorry that this problem did not be solved before 1.0.14. But I it is the latest version when I download.

**Comment by Leiouflying** [comment]
I cleaned the data of the browser, but the problem did not be moved.
There are some picture:
![WRONG](https://leiouflying.cc/wp-content/uploads/2017/06/Screenshot_20170626_061800-300x46.png)This one is the problem.
![correct](https://leiouflying.cc/wp-content/uploads/2017/06/Screenshot_20170626_061919-300x182.png)This one is the correct version.

I think it can help you to solve this problem. I cannot find any change in the 1.0.14 version except the code change.
