### ISSUE TITLE
The picture has been stretched

### ISSUE THREAD

**Issue by Leiouflying** [hayo-studio/Alnico#28]
The picture has been stretched on the index page. I think you can try to cut the center of the picture to show on the index page. Cut the corner of the picture may be a good way too.(Such as cut the upper part  of the picture then scaled). However, make some cutting pictures way and let the users to choose what they prefer may be the best way.
I hope your theme will become more and more powerful.

**Comment by Snownee** [comment]
特色图像请务必使用 752x216。

至于裁剪这个功能我觉得应该由插件或者WP实现。
