### ISSUE TITLE
外链图片显示有问题

### ISSUE THREAD

**Issue by ghost** [hayo-studio/Alnico#29]
http://bogon.me/2017/06/21/steinsgate/

使用的是imgur外链

**Comment by Snownee** [comment]
有怎样的问题？我这里正常显示。

**Comment by ghost** [comment]
貌似缩放有问题
第一张图片是 [来自steam](https://steamuserimages-a.akamaihd.net/ugc/767148225354150721/1EEFBB471BC3E2472A12A6D7079E5630F080B001/) 你可以比对一下

**Comment by ghost** [comment]
这是我看到的页面，不知和你看到的是否相同？
http://imgur.com/Kd8RACt
